export enum ApiErrorCode {
  // 輸入驗證錯誤 (1000-1999)
  INVALID_INPUT = 'INVALID_INPUT',
  MISSING_REQUIRED_HEADER = 'MISSING_REQUIRED_HEADER',
  INVALID_REQUEST_FORMAT = 'INVALID_REQUEST_FORMAT',

  // 業務邏輯錯誤 (2000-2999)
  SUPPLIER_IDS_IDENTICAL = 'SUPPLIER_IDS_IDENTICAL',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',

  // 外部服務錯誤 (3000-3999)
  EXTERNAL_API_UNREACHABLE = 'EXTERNAL_API_UNREACHABLE',
  EXTERNAL_API_ERROR = 'EXTERNAL_API_ERROR',
  EXTERNAL_API_INVALID_RESPONSE = 'EXTERNAL_API_INVALID_RESPONSE',
  EXTERNAL_API_TIMEOUT = 'EXTERNAL_API_TIMEOUT',

  // 系統錯誤 (5000-5999)
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  // 認證與授權錯誤 (4000-4999) - 預留未來擴展
  AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
  AUTHORIZATION_FAILED = 'AUTHORIZATION_FAILED',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
}
